serverAddr = "127.0.0.1"
serverPort = 7000

log.to = "./log/frpc.log"
log.level = "info"
log.maxDays = 3

auth.token = "abc"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
transport.useEncryption = true
transport.useCompression = true
